#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

-define(EXPRESSION, "((tette || culo) ^ cesso) && !vagina").

main(["single"]) ->
  {MicroSeconds, _} = timer:tc(fun() -> booerlang:eval(?EXPRESSION), ok end),
  io:format("Execution time: ~fs~n", [MicroSeconds * (math:pow(10, -6))]);
main(_) ->
  {MicroSeconds, _} = timer:tc(fun() -> [booerlang:eval(?EXPRESSION) || _ <- lists:seq(1, 10000)], ok end),
  io:format("Execution time: ~fs~n", [MicroSeconds * (math:pow(10, -6))]).
